services:
  - type: web
    name: stockpulse
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # You'll set this in the Render dashboard
    healthCheckPath: /
    autoDeploy: true 